In [4]:
print("Hello, World!")

Hello, World!


In [5]:
# why numpy array - its because they are more efficient than lists for numerical computations

# Importing numpy library

import numpy as np

# creating nump array from a list
array = np.array([1, 2, 3, 4, 5])
print("Numpy Array:", array)

Numpy Array: [1 2 3 4 5]


In [6]:
# creating a numpy array from a tuple

tuple_data = (6, 7, 8, 9, 10)
array_from_tuple = np.array(tuple_data)
print(f'array from tuple: {array_from_tuple}')

array from tuple: [ 6  7  8  9 10]


In [7]:
# indexig 
print(f'first element: {array[0]}')
array[4] #np.int64(5) means that the element at index 4 is of type int64 and has a value of 5. 
# In numpy, the data type of array elements can be specified, and in this case, it indicates that the element is a 64-bit integer.

first element: 1


np.int64(5)

In [8]:
# creating a 2D numpy array
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f'{array_2d}')

# targeting specific element in 2D array
array_2d[0][1] # this will give us the element at row 0 and column 1, which is 2.

# use print to display the actual value
print(f'element at row 0 and column 1: {array_2d[0][1]}')


# the are mutable
array_2d[0][1] = array_2d[0][1] + 2
print(f'updated array: {array}')

[[1 2 3]
 [4 5 6]
 [7 8 9]]
element at row 0 and column 1: 2
updated array: [1 2 3 4 5]


In [9]:
# creating a 3D numpy array
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(f'{array_3d}')


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [10]:
# this is specifying the data type of the array elements.
#  By default, numpy will try to infer the data type based on the input data, 
# but you can explicitly set it using the dtype parameter when creating the array.

# create an array that will be kept in float64 bits
array_float = np.array([1.0, 2.0, 3.0], dtype=np.float64)
print(f'array with float64 data type: {array_float}')


# create an array that will be kept in int64 bits
array_int = np.array([1, 2, 3], dtype=np.int64)
print(f'array with int64 data type: {array_int}')

array with float64 data type: [1. 2. 3.]
array with int64 data type: [1 2 3]


In [11]:
# to see the shape of an array
print(f'shape of array_2d: {array_2d.shape}')
print(f'shape of array_3d: {array_3d.shape}')

shape of array_2d: (3, 3)
shape of array_3d: (2, 2, 2)


In [12]:
a = np.zeros(5) # this will create an array of 5 elements, all initialized to zero.
print(f'array of zeros: {a}')


b  = np.zeros((2,4),dtype=np.int64)
print(f'2D array of zeros: {b}')

# whats the use of zeros - it is used to create an array of a specific shape and data type, filled with zeros.


# 

array of zeros: [0. 0. 0. 0. 0.]
2D array of zeros: [[0 0 0 0]
 [0 0 0 0]]


In [13]:
# Ones
c = np.ones(5,dtype=np.int64) # this will create an array of 5 elements, all initialized to one.
print(f'array of ones: {c}')


d = np.ones((4,4),dtype=np.float64)
print(f'2D array of ones: {d}')



array of ones: [1 1 1 1 1]
2D array of ones: [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [14]:
# empty
# what it does is return an array of the given shape

e = np.empty((3,3))
print(f'empty array: {e}')

# an array cannot be empty so this will still print some random values,
#  but it is not initialized to any specific value.

empty array: [[4.67296746e-307 1.69121096e-306 6.23047842e-307]
 [2.22526399e-307 6.23053614e-307 7.56592338e-307]
 [9.34588061e-307 9.34531022e-307 3.62651150e-317]]


In [15]:
# full returns a new array of given shape and type, filled with fill_value.
f = np.full((7,7), 7, dtype=np.float64) # this will create an array of 7 elements, all initialized to 7.
print(f'array filled with 7: {f}')

array filled with 7: [[7. 7. 7. 7. 7. 7. 7.]
 [7. 7. 7. 7. 7. 7. 7.]
 [7. 7. 7. 7. 7. 7. 7.]
 [7. 7. 7. 7. 7. 7. 7.]
 [7. 7. 7. 7. 7. 7. 7.]
 [7. 7. 7. 7. 7. 7. 7.]
 [7. 7. 7. 7. 7. 7. 7.]]


In [16]:
# # CREATING ARRAYS USING SEQUENCE 
# for  num in f:
#     print(num)

for arr in f:
    for num in arr:
        print(num)

7.0
7.0
7.0
7.0
7.0
7.0
7.0
7.0
7.0
7.0
7.0
7.0
7.0
7.0
7.0
7.0
7.0
7.0
7.0
7.0
7.0
7.0
7.0
7.0
7.0
7.0
7.0
7.0
7.0
7.0
7.0
7.0
7.0
7.0
7.0
7.0
7.0
7.0
7.0
7.0
7.0
7.0
7.0
7.0
7.0
7.0
7.0
7.0
7.0


In [17]:
nums = np.arange(10) # this will create an array of 10 elements, from 0 to 9.
# print(f'arange array: {nums}')

# we could specify the start and end of the range as well
nums_range = np.arange(5, stop=15) # this will create an array of 10 elements, from 5 to 14.
# print(f'arange array with range: {nums_range}')


# we specify the step as well
nums_step = np.arange(0, 20, 2) # this will create an array of even numbers from 0 to 18.
# print(f'arange array with step: {nums_step}')


# linspace - it is used to create an array of evenly spaced numbers over a specified interval.
linspace_array = np.linspace(5, 10, num = 5, dtype =np.int64) # this will create an array of 5 evenly spaced numbers between 5 and 10.
print(f'linspace array: {linspace_array}')
# the mathematical formula for linspace is:
# start + (stop - start) * (num - 1) / (num - 1)

linspace array: [ 5  6  7  8 10]


In [18]:
# CREATNG AN IDENTITY MATRIX
identity_matrix = np.eye(4) # this will create a 4x4 identity matrix
print(f'identity matrix: {identity_matrix}')

identity matrix: [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [23]:
# creating arrays from random numbers
# randint - it is used to create an array of random integers within a specified range.
import random
randint_array = np.random.randint(1,10)
print(f'randint array: {randint_array}')

randint array: 1


In [ ]:
# rand tells us to create an array of random numbers between 0 and 1.
rand_array = np.random.rand(5) * 100 # this will create a 5x1 array of random numbers between 0 and 100.
print(f'rand array: {rand_array}')

rand array: [12.72886628 56.06481945 77.56573282  2.04337243 68.67448558]


In [ ]:
# randn - it is used to create an array of random numbers from a normal distribution with mean 0 and standard deviation 1.
randn_array = np.random.randn(10) # this will create an array of 10 random numbers from a normal distribution.
print(f'randn array: {randn_array}')

randn array: [ 0.90517242  1.44503206  0.18481416 -0.26843526  1.13154181 -0.66621702
 -0.69878809  0.63090334 -2.06471976  0.53461111]


In [ ]:
# changing the shape of an array

# create a 16 element array
array  = np.full((16,),2) # this will create an array of 16 elements, all initialized to the value of the original array.
print (f'array: {array}')

array: [2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]


In [35]:
# to chnage the shape
array = array.reshape(4,4) # this will change the shape of the array to 4x4.
print(f'array with new shape: {array}')

array with new shape: [[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]


In [38]:
nums  = np.arange(20) # this will create an array of 20 elements, from 0 to 19.
print(f'arange array: {nums}')

# to change the shape
nums = nums.reshape(4,5) # this will change the shape of the array to 4x5.
print(f'array with new shape: {nums}')

# why would you want to change the shape of an array - it is because sometimes we need to 
# perform operations on arrays that require them to have a specific shape, or we may want to 
# reshape an array for better visualization or to fit the requirements of a particular algorithm.

arange array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
array with new shape: [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [40]:
# reshaping the reshaped array back to its original shape
nums = nums.reshape(20) # this will change the shape of the array back to its original shape.
print(f'array reshaped back to original shape: {nums}')

array reshaped back to original shape: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [46]:
# indexing and slicing
a = np.random.randint(0,100,size=20) # this will create an array of 20 random integers between 0 and 100.
a = a.reshape(4,5) # this will change the shape of the array to 4x5.
print(f"{a}")

[[53 60 21 47 12]
 [99 37 13 87 79]
 [65 47 85 58 23]
 [88 53 44 34 72]]


In [ ]:
# first row
a[0] # this will print the first row


array([70, 23, 47, 20, 53], dtype=int32)

In [47]:
# first row first column
# a[0:2,0:1] # this will print the first row first column

# a[0:1,0]# thsis gets the first row at index 0 and all columns at index 0, which is the first column of the first row.

# what if we want certain columns from all rows - we can use slicing
a[1:3, 2:4] # this will print the elements from row 1 to 2 and column 2 to 3.

array([[13, 87],
       [85, 58]], dtype=int32)

In [ ]:
# TODO : slicing in Numpy arrays both including negative index slicing
# reshaping ,splitting and sorting 


In [59]:
# functions and attributes

sub_array = np.split(a,5,axis=1) # this will split the array into 4 sub-arrays along the rows.
# print(f'sub arrays: {sub_array}')
print(sub_array[0]) # this will print the first sub-array


[[53]
 [99]
 [65]
 [88]]


In [ ]:
# sorting numpy arrays
np_array = np.array([[5, 2, 9, 1, -5, 6], 
                     [3, 7, 4, 8, 2, -1]])
np_a = np.sort(np_array,axis=0) # this will sort the array in ascending order.
print(f'sorted array: {np_a}')

# on axis 1 is y right?
# 0 is x axis

sorted array: [[ 3  2  4  1 -5 -1]
 [ 5  7  9  8  2  6]]


In [ ]:
# Joining arrays 