In [41]:
print("Hello, World!")

Hello, World!


# Why use NumPy arrays instead of Python lists?
# - NumPy arrays are faster for numeric computing because values are stored in contiguous memory.
# - They allow vectorized operations, so arithmetic works elementwise without explicit Python loops.
# - All elements share the same data type, which makes math operations more efficient.
# - NumPy includes many built-in functions for reshaping, slicing, and linear algebra.



In [42]:
# Importing numpy library

import numpy as np

# creating nump array from a list
array = np.array([1, 2, 3, 4, 5])
print("Numpy Array:", array)

Numpy Array: [1 2 3 4 5]


In [43]:
# creating a numpy array from a tuple

tuple_data = (6, 7, 8, 9, 10)
array_from_tuple = np.array(tuple_data)
print(f'array from tuple: {array_from_tuple}')

array from tuple: [ 6  7  8  9 10]


In [44]:
# indexig 
print(f'first element: {array[0]}')
array[4] #np.int64(5) means that the element at index 4 is of type int64 and has a value of 5. 
# In numpy, the data type of array elements can be specified, and in this case, it indicates that the element is a 64-bit integer.

first element: 1


np.int64(5)

# Multidimensional arrays are identified by the number of dimensions (axes)

# 0D array (scalar)
array_0d = np.array('A')

print(f'0D array: {array_0d}')

print(f'Number of dimensions: {array_0d.ndim}')

# 1D array (vector)
array_1d = np.array(['A', 'B', 'C'])

print(f'\n1D array: {array_1d}')

print(f'Number of dimensions: {array_1d.ndim}')

# 2D array (matrix)
array_2d_str = np.array([['A', 'B', 'C'],
                         ['D', 'E', 'F']])
                         
print(f'\n2D array:\n{array_2d_str}')

print(f'Number of dimensions: {array_2d_str.ndim}')

# 3D array (tensor)
array_3d_str = np.array([[['A', 'B', 'C'],
                          ['D', 'E', 'F']]])
print(f'\n3D array:\n{array_3d_str}')

print(f'Number of dimensions: {array_3d_str.ndim}')

# You can check the number of dimensions using the .ndim attribute

In [85]:
# creating a 2D numpy array
array_2d = np.array([[1, 2, 3],
                     [4, 5, 6], 
                     [7, 8, 9]])
print(f'{array_2d}')

# targeting specific element in 2D array
array_2d[0][1] # this will give us the element at row 0 and column 1, which is 2.

# use print to display the actual value
print(f'element at row 0 and column 1: {array_2d[0][1]}')


# the are mutable
array_2d[0][1] = array_2d[0][1] + 2
print(f'updated array: {array}')


arr = np.array([[['A', 'B', 'C', 'D']],
                [['E', 'F', 'G', 'H']],
                [['I', 'J', 'K', 'L']], 
                [['M', 'N', 'O', 'P']], 
                [['Q', 'R', 'S', 'T']], 
                [['U', 'V', 'W', 'X']]])#this is one row

print(arr.ndim)
print(arr.shape)
print(arr[0,0,0] + arr[4,0,2] + arr[4,0,2])


# 2 rows
arri = np.array([
    [['A', 'B', 'C', 'D'],['E', 'F', 'G', 'H']],
    [['I', 'J', 'K', 'L'],['M', 'N', 'O', 'P']], 
    [['Q', 'R', 'S', 'T'],['U', 'V', 'W', 'X']]])#this is 2 rows

print(arri.ndim)
print(arri.shape)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
element at row 0 and column 1: 2
updated array: [[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]
3
(6, 1, 4)
ASS
3
(3, 2, 4)


In [86]:
# creating a 3D numpy array
array_3d = np.array([[[1, 2], [3, 4]],
                     [[5, 6], [7, 8]]])
print(f'{array_3d.shape}')
print(f'{array_3d}')


(2, 2, 2)
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
# this is specifying the data type of the array elements.
#  By default, numpy will try to infer the data type based on the input data, 
# but you can explicitly set it using the dtype parameter when creating the array.

# create an array that will be kept in float64 bits
array_float = np.array([1.0, 2.0, 3.0], dtype=np.float64)
print(f'array with float64 data type: {array_float}')

# float64 is a data type that represents floating-point numbers using 64 bits.
# the 64 bits represent storage for the number, allowing for a wide range of values and high precision.

# create an array that will be kept in int64 bits
array_int = np.array([1, 2, 3], dtype=np.int64)
print(f'array with int64 data type: {array_int}')

array with float64 data type: [1. 2. 3.]
array with int64 data type: [1 2 3]


In [48]:
# to see the shape of an array
print(f'shape of array_2d: {array_2d.shape}')
print(f'shape of array_3d: {array_3d.shape}')

shape of array_2d: (3, 3)
shape of array_3d: (2, 2, 2)


In [49]:
a = np.zeros(5) # this will create an array of 5 elements, all initialized to zero.
print(f'array of zeros: {a}')


b  = np.zeros((2,4),dtype=np.int64)
print(f'2D array of zeros: {b}')

# whats the use of zeros - it is used to create an array of a specific shape and data type, filled with zeros.


array of zeros: [0. 0. 0. 0. 0.]
2D array of zeros: [[0 0 0 0]
 [0 0 0 0]]


In [50]:
# Ones
c = np.ones(5,dtype=np.int64) # this will create an array of 5 elements, all initialized to one.
print(f'array of ones: {c}')


d = np.ones((4,4),dtype=np.float64)
print(f'2D array of ones: {d}')



array of ones: [1 1 1 1 1]
2D array of ones: [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [51]:
# empty
# what it does is return an array of the given shape

e = np.empty((3,3))
print(f'empty array: {e}')

# an array cannot be empty so this will still print some random values,
#  but it is not initialized to any specific value.

empty array: [[4.9e-324 2.0e-323 1.5e-323]
 [2.0e-323 2.5e-323 3.0e-323]
 [3.5e-323 4.0e-323 4.4e-323]]


In [52]:
# full returns a new array of given shape and type, filled with fill_value.
f = np.full((7,7), 8, dtype=np.float64) # this will create an array of 7x7 elements, all initialized to 8.
print(f'array filled with 8: {f}')

array filled with 8: [[8. 8. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8. 8.]]


In [53]:
# # CREATING ARRAYS USING SEQUENCE 
# for  num in f:
#     print(num)

for arr in f:
    for num in arr:
        print(num)

8.0
8.0
8.0
8.0
8.0
8.0
8.0
8.0
8.0
8.0
8.0
8.0
8.0
8.0
8.0
8.0
8.0
8.0
8.0
8.0
8.0
8.0
8.0
8.0
8.0
8.0
8.0
8.0
8.0
8.0
8.0
8.0
8.0
8.0
8.0
8.0
8.0
8.0
8.0
8.0
8.0
8.0
8.0
8.0
8.0
8.0
8.0
8.0
8.0


In [ ]:
nums = np.arange(10) # this will create an array of 10 elements, from 0 to 9.
# print(f'arange array: {nums}')

# we could specify the start and end of the range as well
nums_range = np.arange(5, stop=15) # this will create an array of 10 elements, from 5 to 14.
# print(f'arange array with range: {nums_range}')


# we specify the step as well
nums_step = np.arange(0, 20, 2) # this will create an array of even numbers from 0 to 18.
print(f'arange array with step: {nums_step}')


# linspace - it is used to create an array of evenly spaced numbers over a specified interval.
linspace_array = np.linspace(5, 10, num = 5, dtype =np.int64) # this will create an array of 5 evenly spaced numbers between 5 and 10.
print(f'linspace array: {linspace_array}')
# the mathematical formula for linspace is:
# start + (stop - start) * (num - 1) / (num - 1)

arange array with step: [ 0  2  4  6  8 10 12 14 16 18 20]
linspace array: [ 5  6  7  8 10]


In [55]:
# CREATNG AN IDENTITY MATRIX
identity_matrix = np.eye(4) # this will create a 4x4 identity matrix
print(f'identity matrix: {identity_matrix}')

identity matrix: [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [90]:
# creating arrays from random numbers
# randint - it is used to create an array of random integers within a specified range.
import random
randint_array = np.random.randint(1,10)
print(f'randint array: {randint_array}')

randint array: 8


In [57]:
# rand tells us to create an array of random numbers between 0 and 1.
rand_array = np.random.rand(5) * 100 # this will create a 5x1 array of random numbers between 0 and 100.
print(f'rand array: {rand_array}')

rand array: [16.31430389 14.42281231 59.51946253 38.38024508 73.7735179 ]


In [58]:
# randn - it is used to create an array of random numbers from a normal distribution with mean 0 and standard deviation 1.
randn_array = np.random.randn(10) # this will create an array of 10 random numbers from a normal distribution.
print(f'randn array: {randn_array}')

randn array: [ 1.02436709  0.9771173   0.02665143 -0.10225726 -2.28019559 -0.47665475
 -0.82191636 -0.73083651  0.20226588  2.37478697]


In [59]:
# changing the shape of an array

# create a 16 element array
array  = np.full((16,),2) # this will create an array of 16 elements, all initialized to the value of the original array.
print (f'array: {array}')

array: [2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]


In [60]:
# to chnage the shape
array = array.reshape(4,4) # this will change the shape of the array to 4x4.
print(f'array with new shape: {array}')

array with new shape: [[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]


In [61]:
nums  = np.arange(20) # this will create an array of 20 elements, from 0 to 19.
print(f'arange array: {nums}')

# to change the shape
nums = nums.reshape(4,5) # this will change the shape of the array to 4x5.
print(f'array with new shape: {nums}')

# why would you want to change the shape of an array - it is because sometimes we need to 
# perform operations on arrays that require them to have a specific shape, or we may want to 
# reshape an array for better visualization or to fit the requirements of a particular algorithm.

arange array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
array with new shape: [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [62]:
# reshaping the reshaped array back to its original shape
nums = nums.reshape(20) # this will change the shape of the array back to its original shape.
print(f'array reshaped back to original shape: {nums}')

array reshaped back to original shape: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [ ]:
# indexing and slicing
a = np.random.randint(0,100,size=20) # this will create an array of 20 random integers between 0 and 100.
a = a.reshape(4,5) # this will change the shape of the array to 4x5.
print(f"{a}")

a[1:3, 2:4] # index 3 will be excluded for slicing in py does not include the last element.

[[55 55 16 57 75]
 [ 6 88 93 47 21]
 [60 83 27 27 93]
 [91 43 63 41 83]]


array([[93, 47],
       [27, 27]], dtype=int32)

In [64]:
# first row
a[0] # this will print the first row


array([97, 29, 69, 80, 39], dtype=int32)

In [93]:
# first row first column
# a[0:2,0:1] # this will print the first row first column

# a[0:1,0]# thsis gets the first row at index 0 and all columns at index 0, which is the first column of the first row.

# what if we want certain columns from all rows - we can use slicing
a[1:3, 2:4] # this will print the elements from row 1 to 2 and column 2 to 3.

array([[52, 98],
       [57, 78]], dtype=int32)

In [66]:
# TODO : slicing in Numpy arrays both including negative index slicing
# reshaping ,splitting and sorting 


In [67]:
# functions and attributes

sub_array = np.split(a,5,axis=1) # this will split the array into 4 sub-arrays along the rows.
# print(f'sub arrays: {sub_array}')
print(sub_array[0]) # this will print the first sub-array


[[97]
 [ 7]
 [64]
 [52]]


In [68]:
# sorting numpy arrays
np_array = np.array([[5, 2, 9, 1, -5, 6], 
                     [3, 7, 4, 8, 2, -1]])
np_a = np.sort(np_array,axis=0) # this will sort the array in ascending order.
print(f'sorted array: {np_a}')

# on axis 1 is y right?
# 0 is x axis

sorted array: [[ 3  2  4  1 -5 -1]
 [ 5  7  9  8  2  6]]


In [69]:
a = np.random.randint(-5,10,16).reshape(4,4) # this will create a 4x4 array of random integers between -5 and 10.
print(a) 

[[ 1 -2 -3  0]
 [ 3  1  5 -1]
 [ 6 -5  8  5]
 [ 3 -2  3  1]]


In [70]:
b = np.random.randint(-5,10,16).reshape(4,4) # this will create a 4x4 array of random integers between -5 and 10.
print(b) 

[[-5 -5  5 -4]
 [ 2  1  2  8]
 [ 9  8 -3  3]
 [ 2  0 -1  0]]


In [71]:
np.vstack((a,b))
# vstack is used to stack arrays in sequence vertically (row wise). 
# It takes a tuple of arrays as input and returns a single array that is 
# the result of stacking the input arrays vertically. In this case,
#  it will stack array 'a' on top of array 'b', resulting in an 8x4 array.

array([[ 1, -2, -3,  0],
       [ 3,  1,  5, -1],
       [ 6, -5,  8,  5],
       [ 3, -2,  3,  1],
       [-5, -5,  5, -4],
       [ 2,  1,  2,  8],
       [ 9,  8, -3,  3],
       [ 2,  0, -1,  0]], dtype=int32)

In [72]:
# Horizontal stacking
np.hstack((a,b))
# hstack is used to stack arrays in sequence horizontally (column wise). 
# It takes a tuple of arrays as input and returns a single array that is 
# the result of stacking the input arrays horizontally. In this case,
#  it will stack array 'a' on the left of array 'b', resulting in an 4x8 array.

array([[ 1, -2, -3,  0, -5, -5,  5, -4],
       [ 3,  1,  5, -1,  2,  1,  2,  8],
       [ 6, -5,  8,  5,  9,  8, -3,  3],
       [ 3, -2,  3,  1,  2,  0, -1,  0]], dtype=int32)

In [73]:
# filtering Arrays
# np.where() # this will return the indices of the elements in array 'a' that are greater than .

c = np.random.randint(0,10,12)
print(c)


[6 5 5 1 1 1 1 3 2 2 5 7]


In [74]:
np.where(c > 5,100,-100) # this will return the indices of the elements =



array([ 100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100,
        100])

In [75]:
#TODO:
#  filtering arrays in numpy
# mask
# where
# extract

In [76]:
# Linear Algebra in numpy
# Multipilcation

np.multiply(a,b) # this will perform element-wise multiplication of arrays 'a' and 'b', 
# resulting in a new array where each element is the product of the corresponding elements in 'a' and 'b'.s


# shortcut for np.multiply

a * b # this will perform element-wise multiplication of arrays 'a' and 'b', 
# resulting in a new array where each element is the product of the corresponding elements in 'a' and 'b'.


array([[ -5,  10, -15,   0],
       [  6,   1,  10,  -8],
       [ 54, -40, -24,  15],
       [  6,   0,  -3,   0]], dtype=int32)

In [77]:
# dot product

np.dot(a,b)
# shortcut for dot product
a @ b # this will perform the dot product of arrays 'a' and 'b', resulting in a new array that is the matrix product of 'a' and 'b'.

array([[-36, -31,  10, -29],
       [ 30,  26,   3,  11],
       [ 42,  29,  -9, -40],
       [ 10,   7,   1, -19]], dtype=int32)

In [78]:
# transpose of an array