In [1]:
print("Hello, World!")

Hello, World!


In [3]:
# why numpy array - its because they are more efficient than lists for numerical computations

# Importing numpy library

import numpy as np

# creating nump array from a list
array = np.array([1, 2, 3, 4, 5])
print("Numpy Array:", array)

Numpy Array: [1 2 3 4 5]


In [5]:
# creating a numpy array from a tuple

tuple_data = (6, 7, 8, 9, 10)
array_from_tuple = np.array(tuple_data)
print(f'array from tuple: {array_from_tuple}')

array from tuple: [ 6  7  8  9 10]


In [8]:
# indexig 
print(f'first element: {array[0]}')
array[4] #np.int64(5) means that the element at index 4 is of type int64 and has a value of 5. 
# In numpy, the data type of array elements can be specified, and in this case, it indicates that the element is a 64-bit integer.

first element: 1


np.int64(5)

In [17]:
# creating a 2D numpy array
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f'{array_2d}')

# targeting specific element in 2D array
array_2d[0][1] # this will give us the element at row 0 and column 1, which is 2.

# use print to display the actual value
print(f'element at row 0 and column 1: {array_2d[0][1]}')


# the are mutable
array_2d[0][1] = array_2d[0][1] + 2
print(f'updated array: {array}')

[[1 2 3]
 [4 5 6]
 [7 8 9]]
element at row 0 and column 1: 2
updated array: [1 2 3 4 5]


In [18]:
# creating a 3D numpy array
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(f'{array_3d}')


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [21]:
# this is specifying the data type of the array elements.
#  By default, numpy will try to infer the data type based on the input data, 
# but you can explicitly set it using the dtype parameter when creating the array.

# create an array that will be kept in float64 bits
array_float = np.array([1.0, 2.0, 3.0], dtype=np.float64)
print(f'array with float64 data type: {array_float}')


# create an array that will be kept in int64 bits
array_int = np.array([1, 2, 3], dtype=np.int64)
print(f'array with int64 data type: {array_int}')

array with float64 data type: [1. 2. 3.]
array with int64 data type: [1 2 3]


In [22]:
# to see the shape of an array
print(f'shape of array_2d: {array_2d.shape}')
print(f'shape of array_3d: {array_3d.shape}')

shape of array_2d: (3, 3)
shape of array_3d: (2, 2, 2)


In [ ]:
a = np.zeros(5) # this will create an array of 5 elements, all initialized to zero.
print(f'array of zeros: {a}')


b  = np.zeros((2,4),dtype=np.int64)
print(f'2D array of zeros: {b}')

# whats the use of zeros - it is used to create an array of a specific shape and data type, filled with zeros.


# 

array of zeros: [0. 0. 0. 0. 0.]
2D array of zeros: [[0 0 0 0]
 [0 0 0 0]]


In [ ]:
# Ones
c = np.ones(5,dtype=np.int64) # this will create an array of 5 elements, all initialized to one.
print(f'array of ones: {c}')


d = np.ones((4,4),dtype=np.float64)
print(f'2D array of ones: {d}')



array of ones: [1 1 1 1 1]
2D array of ones: [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
# empty
# what it does is return an array of the given shape

e = np.empty((3,3))
print(f'empty array: {e}')

# an array cannot be empty so this will still print some random values,
#  but it is not initialized to any specific value.

empty array: [[4.9e-324 9.9e-324 1.5e-323]
 [2.0e-323 2.5e-323 3.0e-323]
 [3.5e-323 4.0e-323 4.4e-323]]


In [39]:
# full returns a new array of given shape and type, filled with fill_value.
f = np.full((7,7), 7, dtype=np.float64) # this will create an array of 7 elements, all initialized to 7.
print(f'array filled with 7: {f}')

array filled with 7: [[7. 7. 7. 7. 7. 7. 7.]
 [7. 7. 7. 7. 7. 7. 7.]
 [7. 7. 7. 7. 7. 7. 7.]
 [7. 7. 7. 7. 7. 7. 7.]
 [7. 7. 7. 7. 7. 7. 7.]
 [7. 7. 7. 7. 7. 7. 7.]
 [7. 7. 7. 7. 7. 7. 7.]]


In [42]:
# # CREATING ARRAYS USING SEQUENCE 
# for  num in f:
#     print(num)

for arr in f:
    for num in arr:
        print(num)

7.0
7.0
7.0
7.0
7.0
7.0
7.0
7.0
7.0
7.0
7.0
7.0
7.0
7.0
7.0
7.0
7.0
7.0
7.0
7.0
7.0
7.0
7.0
7.0
7.0
7.0
7.0
7.0
7.0
7.0
7.0
7.0
7.0
7.0
7.0
7.0
7.0
7.0
7.0
7.0
7.0
7.0
7.0
7.0
7.0
7.0
7.0
7.0
7.0


In [ ]:
nums = np.arange(10) # this will create an array of 10 elements, from 0 to 9.
# print(f'arange array: {nums}')

# we could specify the start and end of the range as well
nums_range = np.arange(5, stop=15) # this will create an array of 10 elements, from 5 to 14.
# print(f'arange array with range: {nums_range}')


# we specify the step as well
nums_step = np.arange(0, 20, 2) # this will create an array of even numbers from 0 to 18.
# print(f'arange array with step: {nums_step}')


# linspace - it is used to create an array of evenly spaced numbers over a specified interval.
linspace_array = np.linspace(5, 10, num = 5, dtype =np.int64) # this will create an array of 5 evenly spaced numbers between 5 and 10.
print(f'linspace array: {linspace_array}')
# the mathematical formula for linspace is:
# start + (stop - start) * (num - 1) / (num - 1)

linspace array: [ 5  6  7  8 10]


In [ ]:
# CREATNG AN IDENTITY MATRIX
identity_matrix = np.eye(4) # this will create a 4x4 identity matrix
print(f'identity matrix: {identity_matrix}')

identity matrix: [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]